# Generated by Django 6.0.7 on 2026-07-10 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'buyers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvest_date', models.DateField()),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_grade', models.CharField(choices=[('grade_a', 'Grade A'), ('grade_b', 'Grade B'), ('grade_c', 'Grade C'), ('mixed', 'Mixed')], default='grade_a', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'harvest_records',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_date', models.DateField()),
                ('kg_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg_ksh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('amount_paid_ksh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-sale_date'],
            },
        ),
    ]
