# Generated by Django 6.0.7 on 2026-07-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('farms', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='planting_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='operations.plantingrecord'),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='commerce.buyer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='harvest_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='commerce.harvestrecord'),
        ),
    ]
