# Generated by Django 6.0.7 on 2026-07-10 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('daily_rate_ksh', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='farms.farm')),
            ],
            options={
                'db_table': 'workers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabourLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('days_worked', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('task_type', models.CharField(choices=[('planting', 'Planting'), ('weeding', 'Weeding'), ('spraying', 'Spraying'), ('harvesting', 'Harvesting'), ('transport', 'Transport'), ('other', 'Other')], default='other', max_length=20)),
                ('total_pay_ksh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planting_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_logs', to='operations.plantingrecord')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='labour.worker')),
            ],
            options={
                'db_table': 'labour_logs',
                'ordering': ['-work_date'],
            },
        ),
    ]
