# Generated by Django 6.0.7 on 2026-07-10 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_planted', models.DateField()),
                ('field_area_acres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantings', to='farms.crop')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantings', to='farms.season')),
            ],
            options={
                'db_table': 'planting_records',
                'ordering': ['-date_planted'],
            },
        ),
        migrations.CreateModel(
            name='InputExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_type', models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('herbicide', 'Herbicide'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=30)),
                ('amount_ksh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_purchased', models.DateField()),
                ('planting_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='operations.plantingrecord')),
            ],
            options={
                'db_table': 'input_expenses',
                'ordering': ['-date_purchased'],
            },
        ),
    ]
